#配置mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vue3_ts_cms?serverTimezone=UTC
    username: root
    password: 210431
  resources:
    static-locations: classpath:/templates/,classpath:/static/

#配置mybatis日志
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


